### ISSUE TITLE
Encoutering database error when going through the guestbook tutorial

### ISSUE THREAD

**Issue by chrissound** [yogthos/luminus#48]
Hi there,

Perhaps I did things in the wrong order, but it seems that if the database was already created upon starting the Luminus application (via `lein ring server`), then it would not recreate the database with the new guestbook table.
So I encountered an error / exception in the form of:
`Table "GUESTBOOK" not found; SQL statement: SELECT "GUESTBOOK".* FROM "GUESTBOOK"`

This was solved by setting a different filename for `db-store`.

Great tutorial otherwise! 

Cheers

**Comment by elliotec** [comment]
I had the same issue. I had to do the following:

$ lein repl

=> (in-ns 'guestbook.db.schema)
=> (require :reload 'guestbook.db.schema)
=> (create-tables)

If I could have figured out how to just drop the database I think that would've worked better. But changing the filename for db-store is another working solution.

**Comment by yogthos** [comment]
latest luminus has been updated to use Ragtime for all db management.
